project:
  type: website

website:
  title: "Francisco Blasco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    toc: true

